// rfce
import Link from "next/link";
import React from "react";
export const metadata = {
  title: "About Page Metadata",
  description: "Generated by create next app",
};
function AboutLayout({ children }) {
  return (
    <div>
      <nav className="flex justify-center gap-x-3">
        <Link href="/about/mission">Mission</Link> |{" "}
        <Link href="/about/vision">Vision</Link>{" "}
      </nav>
      {children}
    </div>
  );
}

export default AboutLayout;
