import { Inter } from "next/font/google";
import "./globals.css";
import Link from "next/link";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};
// react functional component
export default function RootLayout({ children }) {
  return (
    <html lang="en" className="p-6">
      <body className={inter.className}>
        <nav className="flex gap-x-3 justify-end pr-[30px]">
          <Link href="/">Home</Link>| <Link href="/about">About</Link> |{" "}
          <Link href="/blogs">Blogs</Link> |<Link href="/posts">Posts</Link>
        </nav>
        <hr />
        {children}
      </body>
    </html>
  );
}
